//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indulged.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indulged.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be empty.
        /// </summary>
        public static string CommentCannotBeNullText {
            get {
                return ResourceManager.GetString("CommentCannotBeNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentComposerTitleText {
            get {
                return ResourceManager.GetString("CommentComposerTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding comment.
        /// </summary>
        public static string CommentPostErrorText {
            get {
                return ResourceManager.GetString("CommentPostErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting comment.
        /// </summary>
        public static string CommentPostingText {
            get {
                return ResourceManager.GetString("CommentPostingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load contact list.
        /// </summary>
        public static string ContactsLoadingErrorText {
            get {
                return ResourceManager.GetString("ContactsLoadingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving contacts.
        /// </summary>
        public static string ContactsLoadingText {
            get {
                return ResourceManager.GetString("ContactsLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactsPageTitleText {
            get {
                return ResourceManager.GetString("ContactsPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prelude.
        /// </summary>
        public static string DashboardPreludeText {
            get {
                return ResourceManager.GetString("DashboardPreludeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string DashboardSummersaltText {
            get {
                return ResourceManager.GetString("DashboardSummersaltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string DashboardVioletText {
            get {
                return ResourceManager.GetString("DashboardVioletText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been added as fvourite.
        /// </summary>
        public static string DetailPageAddedFavText {
            get {
                return ResourceManager.GetString("DetailPageAddedFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string DetailPageCommentsText {
            get {
                return ResourceManager.GetString("DetailPageCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIF data is not available.
        /// </summary>
        public static string DetailPageEXIFNotAvailableText {
            get {
                return ResourceManager.GetString("DetailPageEXIFNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIF Info.
        /// </summary>
        public static string DetailPageEXIFTitleText {
            get {
                return ResourceManager.GetString("DetailPageEXIFTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load comments.
        /// </summary>
        public static string DetailPageLoadCommentsErrorText {
            get {
                return ResourceManager.GetString("DetailPageLoadCommentsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve EXIF Info.
        /// </summary>
        public static string DetailPageLoadEXIFErrorText {
            get {
                return ResourceManager.GetString("DetailPageLoadEXIFErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading comments.
        /// </summary>
        public static string DetailPageLoadingCommentsText {
            get {
                return ResourceManager.GetString("DetailPageLoadingCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading EXIF Info.
        /// </summary>
        public static string DetailPageLoadingEXIFText {
            get {
                return ResourceManager.GetString("DetailPageLoadingEXIFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading photo ....
        /// </summary>
        public static string DetailPageLoadingPhotoText {
            get {
                return ResourceManager.GetString("DetailPageLoadingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking photo as favourite.
        /// </summary>
        public static string DetailPageMarkingAsFavText {
            get {
                return ResourceManager.GetString("DetailPageMarkingAsFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo does not have any comments.
        /// </summary>
        public static string DetailPageNoCommentsText {
            get {
                return ResourceManager.GetString("DetailPageNoCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This photo does not have any tags.
        /// </summary>
        public static string DetailPageNoTagsText {
            get {
                return ResourceManager.GetString("DetailPageNoTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been removed from favourite list.
        /// </summary>
        public static string DetailPageRemovedFavText {
            get {
                return ResourceManager.GetString("DetailPageRemovedFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing photo from favourite.
        /// </summary>
        public static string DetailPageRemovingFavText {
            get {
                return ResourceManager.GetString("DetailPageRemovingFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get photo info.
        /// </summary>
        public static string DetailPageRetrievePhotoInfoErrorText {
            get {
                return ResourceManager.GetString("DetailPageRetrievePhotoInfoErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving photo info.
        /// </summary>
        public static string DetailPageRetrievingPhotoInfoText {
            get {
                return ResourceManager.GetString("DetailPageRetrievingPhotoInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string DetailPageTagsTitleText {
            get {
                return ResourceManager.GetString("DetailPageTagsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view all ....
        /// </summary>
        public static string DetailPageViewAllCommentsText {
            get {
                return ResourceManager.GetString("DetailPageViewAllCommentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load discovery stream.
        /// </summary>
        public static string DiscoveryPageLoadingErrorText {
            get {
                return ResourceManager.GetString("DiscoveryPageLoadingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string DiscoveryPageTitleText {
            get {
                return ResourceManager.GetString("DiscoveryPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while replying message.
        /// </summary>
        public static string DiscussionPostingErrorText {
            get {
                return ResourceManager.GetString("DiscussionPostingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting to discussion board.
        /// </summary>
        public static string DiscussionPostingText {
            get {
                return ResourceManager.GetString("DiscussionPostingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving replies.
        /// </summary>
        public static string DiscussionRetrievingRepliesText {
            get {
                return ResourceManager.GetString("DiscussionRetrievingRepliesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load favourite photos.
        /// </summary>
        public static string FavPageLoadingErrorText {
            get {
                return ResourceManager.GetString("FavPageLoadingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string FavPageTitleText {
            get {
                return ResourceManager.GetString("FavPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string GenericAgreeText {
            get {
                return ResourceManager.GetString("GenericAgreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GenericCancelText {
            get {
                return ResourceManager.GetString("GenericCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string GenericConfirmText {
            get {
                return ResourceManager.GetString("GenericConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string GenericDoneText {
            get {
                return ResourceManager.GetString("GenericDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GenericErrorTitleText {
            get {
                return ResourceManager.GetString("GenericErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading stream ....
        /// </summary>
        public static string GenericLoadingStreamText {
            get {
                return ResourceManager.GetString("GenericLoadingStreamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content found.
        /// </summary>
        public static string GenericNoContentFound {
            get {
                return ResourceManager.GetString("GenericNoContentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load photos.
        /// </summary>
        public static string GenericPhotoLoadingErrorText {
            get {
                return ResourceManager.GetString("GenericPhotoLoadingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request.
        /// </summary>
        public static string GenericSendingRequestText {
            get {
                return ResourceManager.GetString("GenericSendingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string GenericUntitledText {
            get {
                return ResourceManager.GetString("GenericUntitledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting ....
        /// </summary>
        public static string GenericWaitingText {
            get {
                return ResourceManager.GetString("GenericWaitingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Adding Photos.
        /// </summary>
        public static string GroupAddToGroupDoneText {
            get {
                return ResourceManager.GetString("GroupAddToGroupDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Group.
        /// </summary>
        public static string GroupAddToGroupTitleText {
            get {
                return ResourceManager.GetString("GroupAddToGroupTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding topic.
        /// </summary>
        public static string GroupAddTopicErrorText {
            get {
                return ResourceManager.GetString("GroupAddTopicErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string GroupBrowseText {
            get {
                return ResourceManager.GetString("GroupBrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discussions.
        /// </summary>
        public static string GroupDiscussionHeaderText {
            get {
                return ResourceManager.GetString("GroupDiscussionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        public static string GroupDiscussionTitleText {
            get {
                return ResourceManager.GetString("GroupDiscussionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Request.
        /// </summary>
        public static string GroupInvitationRequestText {
            get {
                return ResourceManager.GetString("GroupInvitationRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Group.
        /// </summary>
        public static string GroupJoiningText {
            get {
                return ResourceManager.GetString("GroupJoiningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Group.
        /// </summary>
        public static string GroupJoinText {
            get {
                return ResourceManager.GetString("GroupJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading photo collection.
        /// </summary>
        public static string GroupLoadingPhotoCollectionText {
            get {
                return ResourceManager.GetString("GroupLoadingPhotoCollectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading photos.
        /// </summary>
        public static string GroupLoadingPhotosText {
            get {
                return ResourceManager.GetString("GroupLoadingPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading topics.
        /// </summary>
        public static string GroupLoadingTopicsText {
            get {
                return ResourceManager.GetString("GroupLoadingTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Membership Request.
        /// </summary>
        public static string GroupMembershipText {
            get {
                return ResourceManager.GetString("GroupMembershipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active topics.
        /// </summary>
        public static string GroupNoActiveTopicsText {
            get {
                return ResourceManager.GetString("GroupNoActiveTopicsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string GroupPhotoHeaderText {
            get {
                return ResourceManager.GetString("GroupPhotoHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing photo.
        /// </summary>
        public static string GroupRemovingPhotoText {
            get {
                return ResourceManager.GetString("GroupRemovingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent to group admin.
        /// </summary>
        public static string GroupRequestSentText {
            get {
                return ResourceManager.GetString("GroupRequestSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving group info.
        /// </summary>
        public static string GroupRetrievingInfoText {
            get {
                return ResourceManager.GetString("GroupRetrievingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Rules.
        /// </summary>
        public static string GroupRulesText {
            get {
                return ResourceManager.GetString("GroupRulesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending request.
        /// </summary>
        public static string GroupSendingRequestText {
            get {
                return ResourceManager.GetString("GroupSendingRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string GroupSendRequestText {
            get {
                return ResourceManager.GetString("GroupSendRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject and content cannot be empty.
        /// </summary>
        public static string GroupSubjectContentCannotBeEmptyText {
            get {
                return ResourceManager.GetString("GroupSubjectContentCannotBeEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Indulged.
        /// </summary>
        public static string LoginAboutAppTitleText {
            get {
                return ResourceManager.GetString("LoginAboutAppTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string LoginAboutText {
            get {
                return ResourceManager.GetString("LoginAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot authenticate with Flickr at this time.
        /// </summary>
        public static string LoginAuthErrorText {
            get {
                return ResourceManager.GetString("LoginAuthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LoginBackText {
            get {
                return ResourceManager.GetString("LoginBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoginLoadingText {
            get {
                return ResourceManager.GetString("LoginLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string LoginSignInText {
            get {
                return ResourceManager.GetString("LoginSignInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts.
        /// </summary>
        public static string MainPageAppBarContactsText {
            get {
                return ResourceManager.GetString("MainPageAppBarContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string MainPageAppBarFeedbackText {
            get {
                return ResourceManager.GetString("MainPageAppBarFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string MainPageAppBarLogoutText {
            get {
                return ResourceManager.GetString("MainPageAppBarLogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string MainPageAppBarMyProfileText {
            get {
                return ResourceManager.GetString("MainPageAppBarMyProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string MainPageAppBarRefreshText {
            get {
                return ResourceManager.GetString("MainPageAppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageAppBarSearchText {
            get {
                return ResourceManager.GetString("MainPageAppBarSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPageAppBarSettingsText {
            get {
                return ResourceManager.GetString("MainPageAppBarSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription settings.
        /// </summary>
        public static string MainPageAppBarSubscriptionText {
            get {
                return ResourceManager.GetString("MainPageAppBarSubscriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload photo.
        /// </summary>
        public static string MainPageAppBarUploadPhotoText {
            get {
                return ResourceManager.GetString("MainPageAppBarUploadPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string MainPageLogoutButtonText {
            get {
                return ResourceManager.GetString("MainPageLogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be taken back to login screen and your privacy will be cleared out on this device.
        /// </summary>
        public static string MainPageLogoutContentText {
            get {
                return ResourceManager.GetString("MainPageLogoutContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string MainPageLogoutTitleText {
            get {
                return ResourceManager.GetString("MainPageLogoutTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string MainPageSubscriptionTitleText {
            get {
                return ResourceManager.GetString("MainPageSubscriptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any contacts.
        /// </summary>
        public static string NoContactsText {
            get {
                return ResourceManager.GetString("NoContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding photo.
        /// </summary>
        public static string PhotoCollectionAddingPhotoText {
            get {
                return ResourceManager.GetString("PhotoCollectionAddingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Photo Set.
        /// </summary>
        public static string PhotoCollectionAddToSetText {
            get {
                return ResourceManager.GetString("PhotoCollectionAddToSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading photo collection.
        /// </summary>
        public static string PhotoCollectionLoadingText {
            get {
                return ResourceManager.GetString("PhotoCollectionLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been added to set.
        /// </summary>
        public static string PhotoCollectionPhotoAddedText {
            get {
                return ResourceManager.GetString("PhotoCollectionPhotoAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been removed from set.
        /// </summary>
        public static string PhotoCollectionPhotoRemovedText {
            get {
                return ResourceManager.GetString("PhotoCollectionPhotoRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing photo.
        /// </summary>
        public static string PhotoCollectionRemovingPhotoText {
            get {
                return ResourceManager.GetString("PhotoCollectionRemovingPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to community.
        /// </summary>
        public static string PreludeCommunitySectionText {
            get {
                return ResourceManager.GetString("PreludeCommunitySectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string PreludeContactsItemText {
            get {
                return ResourceManager.GetString("PreludeContactsItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        public static string PreludeDiscoveryItemText {
            get {
                return ResourceManager.GetString("PreludeDiscoveryItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        public static string PreludeFavItemText {
            get {
                return ResourceManager.GetString("PreludeFavItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured.
        /// </summary>
        public static string PreludeFeaturedSectionText {
            get {
                return ResourceManager.GetString("PreludeFeaturedSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Photo Stream.
        /// </summary>
        public static string PreludeMyPhotoStreamItemText {
            get {
                return ResourceManager.GetString("PreludeMyPhotoStreamItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups found.
        /// </summary>
        public static string PreludeNoGroupFoundText {
            get {
                return ResourceManager.GetString("PreludeNoGroupFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo sets found.
        /// </summary>
        public static string PreludeNoPhotoSetFoundText {
            get {
                return ResourceManager.GetString("PreludeNoPhotoSetFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo sets.
        /// </summary>
        public static string PreludePhotoSetSectionText {
            get {
                return ResourceManager.GetString("PreludePhotoSetSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving group list ....
        /// </summary>
        public static string PreludeRetrievingGroupsText {
            get {
                return ResourceManager.GetString("PreludeRetrievingGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving photo sets ....
        /// </summary>
        public static string PreludeRetrievingPhotoSetsText {
            get {
                return ResourceManager.GetString("PreludeRetrievingPhotoSetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to retry.
        /// </summary>
        public static string PreludeRetryText {
            get {
                return ResourceManager.GetString("PreludeRetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string PreludeSearchItemText {
            get {
                return ResourceManager.GetString("PreludeSearchItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PreludeSummersaltItemText {
            get {
                return ResourceManager.GetString("PreludeSummersaltItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string PreludeUploadPhotoItemText {
            get {
                return ResourceManager.GetString("PreludeUploadPhotoItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Stream.
        /// </summary>
        public static string PreludeVioletItemText {
            get {
                return ResourceManager.GetString("PreludeVioletItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Camera ....
        /// </summary>
        public static string ProCamInitText {
            get {
                return ResourceManager.GetString("ProCamInitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProfilePageDescText {
            get {
                return ResourceManager.GetString("ProfilePageDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading profile ....
        /// </summary>
        public static string ProfilePageLoadingText {
            get {
                return ResourceManager.GetString("ProfilePageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ProfilePageLocationText {
            get {
                return ResourceManager.GetString("ProfilePageLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo yet.
        /// </summary>
        public static string ProfilePageNoPhotoText {
            get {
                return ResourceManager.GetString("ProfilePageNoPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo uploaded.
        /// </summary>
        public static string ProfilePagePhotoCountText {
            get {
                return ResourceManager.GetString("ProfilePagePhotoCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string ProfilePagePhotoHeaderText {
            get {
                return ResourceManager.GetString("ProfilePagePhotoHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string ProfilePageProfileHeaderText {
            get {
                return ResourceManager.GetString("ProfilePageProfileHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real name.
        /// </summary>
        public static string ProfilePageRealNameText {
            get {
                return ResourceManager.GetString("ProfilePageRealNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile link.
        /// </summary>
        public static string ProfilePageUrlText {
            get {
                return ResourceManager.GetString("ProfilePageUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply cannot be empty.
        /// </summary>
        public static string ReplyCannotBeEmptyText {
            get {
                return ResourceManager.GetString("ReplyCannotBeEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching groups.
        /// </summary>
        public static string SearchingGroupsText {
            get {
                return ResourceManager.GetString("SearchingGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching photos.
        /// </summary>
        public static string SearchingPhotosText {
            get {
                return ResourceManager.GetString("SearchingPhotosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string SearchResultGroupHeaderText {
            get {
                return ResourceManager.GetString("SearchResultGroupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string SearchResultPhotoHeaderText {
            get {
                return ResourceManager.GetString("SearchResultPhotoHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indulged is able to render a blurred background when viewing photos. This however may cause rendering glithes and is turned off by default.
        /// </summary>
        public static string SettingsBlurBackgroundDescText {
            get {
                return ResourceManager.GetString("SettingsBlurBackgroundDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Blurred Background.
        /// </summary>
        public static string SettingsBlurBackgroundText {
            get {
                return ResourceManager.GetString("SettingsBlurBackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The built-in ProCam camera provides manual focusing, ISO and aperture support, but is still considered experimental at this version thus is not enabled by default.
        /// </summary>
        public static string SettingsCameraDescText {
            get {
                return ResourceManager.GetString("SettingsCameraDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string SettingsCameraHeaderText {
            get {
                return ResourceManager.GetString("SettingsCameraHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ProCam.
        /// </summary>
        public static string SettingsProCamText {
            get {
                return ResourceManager.GetString("SettingsProCamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsProFXDarkText {
            get {
                return ResourceManager.GetString("SettingsProFXDarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFX is the image processing module for Indulged. This settings decides whether to use a light or a dark background when editing images.
        /// </summary>
        public static string SettingsProFXDescText {
            get {
                return ResourceManager.GetString("SettingsProFXDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProFX.
        /// </summary>
        public static string SettingsProFXHeaderText {
            get {
                return ResourceManager.GetString("SettingsProFXHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsProFXLightText {
            get {
                return ResourceManager.GetString("SettingsProFXLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        public static string SettingsRenderingHeaderText {
            get {
                return ResourceManager.GetString("SettingsRenderingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose to subscribe one of these streams and the photos will appear in the &apos;violet&apos; section of the app.
        /// </summary>
        public static string SettingsSubscriptionDescText {
            get {
                return ResourceManager.GetString("SettingsSubscriptionDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string SettingsSubscriptionHeaderText {
            get {
                return ResourceManager.GetString("SettingsSubscriptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Stream.
        /// </summary>
        public static string SubscriptionDiscoveryText {
            get {
                return ResourceManager.GetString("SubscriptionDiscoveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Stream.
        /// </summary>
        public static string SubscriptionFavText {
            get {
                return ResourceManager.GetString("SubscriptionFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Photo Stream.
        /// </summary>
        public static string SubscriptionMyPhotoStreamText {
            get {
                return ResourceManager.GetString("SubscriptionMyPhotoStreamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added this photo as favourite.
        /// </summary>
        public static string SummersaltAddedFavText {
            get {
                return ResourceManager.GetString("SummersaltAddedFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        public static string SummersaltAndText {
            get {
                return ResourceManager.GetString("SummersaltAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  commented on .
        /// </summary>
        public static string SummersaltCommentedOnText {
            get {
                return ResourceManager.GetString("SummersaltCommentedOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other people added this photo as favourite.
        /// </summary>
        public static string SummersaltMultiFavText {
            get {
                return ResourceManager.GetString("SummersaltMultiFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extra info available.
        /// </summary>
        public static string SummersaltNoInfoFoundText {
            get {
                return ResourceManager.GetString("SummersaltNoInfoFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activities.
        /// </summary>
        public static string SummersaltRecentActivityText {
            get {
                return ResourceManager.GetString("SummersaltRecentActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving user info ....
        /// </summary>
        public static string SummersaltRetrievingUserInfoText {
            get {
                return ResourceManager.GetString("SummersaltRetrievingUserInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Contacts.
        /// </summary>
        public static string SummersaltShowAllContactsText {
            get {
                return ResourceManager.GetString("SummersaltShowAllContactsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and 1 other person added this photo as favourite.
        /// </summary>
        public static string SummersaltSingleFavText {
            get {
                return ResourceManager.GetString("SummersaltSingleFavText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since .
        /// </summary>
        public static string SummersaltUserInfoMemberSinceText {
            get {
                return ResourceManager.GetString("SummersaltUserInfoMemberSinceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo uploaded: .
        /// </summary>
        public static string SummersaltUserInfoPhotoUploadedText {
            get {
                return ResourceManager.GetString("SummersaltUserInfoPhotoUploadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached limitation.
        /// </summary>
        public static string ThrottleReachedErrorText {
            get {
                return ResourceManager.GetString("ThrottleReachedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        public static string TopicComposerBodyText {
            get {
                return ResourceManager.GetString("TopicComposerBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string TopicComposerSubjectText {
            get {
                return ResourceManager.GetString("TopicComposerSubjectText", resourceCulture);
            }
        }
    }
}
